### ISSUE TITLE
Affect entire lit

### ISSUE THREAD

**Issue by sichtbeton** [alter-alter/DelugeFirmware#1] opened 2023-06-11 13:31 UTC
First of all: thank you so much for creating this! It finally opens up the kit mode. 16 levels too? Freaking genius. Thank you.

One minor thing that I found, was that the affect entire button was lit all the time even when explicitly pressed. This is a bit irritating when for example adjusting parameters for a single kit item. Nothing big, just a small detail.

Again: awesome!

https://github.com/alter-alter/DelugeFirmware/assets/62035517/7cbbc9f1-ee3c-47d6-99a1-3b7e0e20328a

**Comment by ok-reza** [comment] 2023-06-12 02:51
Good eye! Glad both functions work properly despite the button always being lit. It might be because non-KIT clips are forced to be AFFECT ENTIRE and this code piggy backs on the previous Keyboard view.

**Comment by sichtbeton** [comment] 2023-06-12 11:44
I have no clue about code. but I really like that this is possible now! Yeah... And about what code does what... I have no clue at all.

**Comment by alter-alter** [comment] 2023-06-15 03:20
This issue has been fixed in version 1.0.3. Please try it.
https://github.com/alter-alter/DelugeFirmware/releases

**Comment by suivaht** [comment] 2023-06-15 14:27
I can confirm that as of 1.0.3 this specific issue is resolved.  Excellent work and great progress...

**Closed as completed** 2023-06-16 05:46 UTC

**Comment by sichtbeton** [comment] 2023-06-19 14:55
you are great! thank you.
